# Generated by Django 3.1.7 on 2021-04-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('addr', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('doctorname', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Appointments',
            },
        ),
    ]
